const { test, after } = require('node:test');
const assert = require('node:assert/strict');
const { mkdtempSync, writeFileSync, rmSync } = require('node:fs');
const { join, resolve } = require('node:path');
const { tmpdir } = require('node:os');
const { spawnSync } = require('node:child_process');

const guardPath = resolve(__dirname, '../../scripts/commit-msg-guard.sh');
const tempDirs = [];

function makeTempDir(prefix) {
  const dir = mkdtempSync(join(tmpdir(), prefix));
  tempDirs.push(dir);
  return dir;
}

function runGuard(message, env = {}) {
  const dir = makeTempDir('sd0x-commit-msg-');
  const msgFile = join(dir, 'COMMIT_EDITMSG');
  writeFileSync(msgFile, message);
  return spawnSync('bash', [guardPath, msgFile], {
    encoding: 'utf8',
    env: { ...process.env, ...env },
  });
}

after(() => {
  for (const dir of tempDirs) {
    rmSync(dir, { recursive: true, force: true });
  }
});

// ============================================================================
// Happy path — normal commit messages must pass
// ============================================================================

test('plain conventional commit passes', () => {
  const result = runGuard('feat: add session reset logic\n\nDetails here.\n');
  assert.equal(result.status, 0);
});

test('developer co-author trailer passes', () => {
  const result = runGuard(
    'fix: guard notebook edits\n\nCo-Authored-By: SD0 <lf2sam111@gmail.com>\n'
  );
  assert.equal(result.status, 0);
});

// ============================================================================
// Word-boundary false positives — every message below used to be rejected
// because bare `AI`/`GPT` under -i matched inside ordinary words
// ============================================================================

test('FP regression: "Generated by the maintainer" passes ("ai" inside maintainer)', () => {
  const result = runGuard('docs: update runbook\n\nGenerated by the maintainer script.\n');
  assert.equal(result.status, 0, result.stderr);
});

test('FP regression: "Generated with detailed steps" passes ("ai" inside detailed)', () => {
  const result = runGuard('docs: release notes\n\nGenerated with detailed steps for QA.\n');
  assert.equal(result.status, 0, result.stderr);
});

test('FP regression: "Generated by domain tooling" passes ("ai" inside domain)', () => {
  const result = runGuard('chore: regen fixtures\n\nGenerated by domain tooling.\n');
  assert.equal(result.status, 0, result.stderr);
});

test('FP regression: robot emoji + "maintainer" passes', () => {
  const result = runGuard('feat: add bot avatar 🤖 for maintainer dashboard\n');
  assert.equal(result.status, 0, result.stderr);
});

// GPT is intentionally UNbounded (unlike AI): no ordinary English word contains
// "gpt", and the unbounded form is what catches ChatGPT / GPT-4 / GPT4. The cost
// is that a contrived name like "GPTools" is also blocked — an acceptable trade
// (not an ordinary word; ALLOW_AI_COAUTHOR=1 is the escape hatch).
test('blocks "GPTools" name (GPT intentionally unbounded to catch ChatGPT/GPT-4)', () => {
  const result = runGuard(
    'chore: sync\n\nCo-Authored-By: GPTools Bot <bot@gptools.example>\n'
  );
  assert.equal(result.status, 1);
});

// ============================================================================
// True positives — AI attribution must still be rejected
// ============================================================================

test('blocks Co-Authored-By Claude trailer', () => {
  const result = runGuard(
    'feat: x\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n'
  );
  assert.equal(result.status, 1);
  assert.match(result.stderr, /AI attribution detected/);
});

test('blocks "Generated with Claude Code" tag', () => {
  const result = runGuard('feat: x\n\n🔧 Generated with Claude Code\n');
  assert.equal(result.status, 1);
});

test('blocks standalone "Generated by AI" tag', () => {
  const result = runGuard('feat: x\n\nGenerated by AI assistant\n');
  assert.equal(result.status, 1);
});

test('blocks "Generated by GPT-4" tag', () => {
  const result = runGuard('feat: x\n\nGenerated by GPT-4\n');
  assert.equal(result.status, 1);
});

// Regression: bounding GPT with \b silently dropped ChatGPT/OpenAI (the two most
// common AI trailers) because CamelCase has no word boundary inside them. These
// pin that the guard blocks them again.
test('blocks "Generated with ChatGPT" (unbounded GPT covers ChatGPT)', () => {
  const result = runGuard('feat: x\n\nGenerated with ChatGPT\n');
  assert.equal(result.status, 1);
});

test('blocks "Generated by OpenAI Codex" (explicit OpenAI alternative)', () => {
  const result = runGuard('feat: x\n\nGenerated by OpenAI Codex\n');
  assert.equal(result.status, 1);
});

test('blocks robot emoji + ChatGPT attribution', () => {
  const result = runGuard('feat: x\n\n🤖 Generated with ChatGPT\n');
  assert.equal(result.status, 1);
});

test('blocks "Co-Authored-By: ChatGPT" trailer', () => {
  const result = runGuard('feat: x\n\nCo-Authored-By: ChatGPT <bot@example.com>\n');
  assert.equal(result.status, 1);
});

test('blocks robot emoji with Claude attribution', () => {
  const result = runGuard('feat: x\n\n🤖 Generated with [Claude Code](https://claude.com)\n');
  assert.equal(result.status, 1);
});

// ============================================================================
// Escape hatch + error handling
// ============================================================================

test('ALLOW_AI_COAUTHOR=1 bypasses the guard', () => {
  const result = runGuard(
    'feat: x\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n',
    { ALLOW_AI_COAUTHOR: '1' }
  );
  assert.equal(result.status, 0);
});

test('missing message file exits 1 with error', () => {
  const result = spawnSync('bash', [guardPath, '/nonexistent/COMMIT_EDITMSG'], {
    encoding: 'utf8',
    env: { ...process.env },
  });
  assert.equal(result.status, 1);
  assert.match(result.stderr, /file not found/);
});
