const { test } = require('node:test');
const assert = require('node:assert/strict');
const { resolve } = require('node:path');
const { statSync, writeFileSync, mkdtempSync, rmSync } = require('node:fs');
const { spawnSync } = require('node:child_process');
const { tmpdir } = require('node:os');

const guardPath = resolve(__dirname, '../../scripts/commit-msg-guard.sh');

// Helper: run guard script with a message, return { status, output }
function runGuard(message, env = {}) {
  const tmpDir = mkdtempSync(resolve(tmpdir(), 'smart-commit-test-'));
  const msgFile = resolve(tmpDir, 'COMMIT_MSG');
  writeFileSync(msgFile, message);
  try {
    const result = spawnSync('bash', [guardPath, msgFile], {
      encoding: 'utf8',
      env: { ...process.env, ...env },
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    return {
      status: result.status,
      output: (result.stdout || '') + (result.stderr || ''),
    };
  } finally {
    rmSync(tmpDir, { recursive: true, force: true });
  }
}

// Helper: run validate_msg inline shell function
// NOTE: This intentionally duplicates the validate_msg logic from SKILL.md Step 5c.
// It tests the documented behavior spec, not a shared import. If the SKILL.md
// patterns change, these tests must be updated in sync.
function runValidateMsg(message, aiCoAuthor = false) {
  const tmpDir = mkdtempSync(resolve(tmpdir(), 'smart-commit-validate-'));
  const msgFile = resolve(tmpDir, 'MSG');
  writeFileSync(msgFile, message);
  const script = `
AI_CO_AUTHOR="${aiCoAuthor ? '1' : '0'}"

validate_msg() {
  local tmpfile="$1"
  if [ "$AI_CO_AUTHOR" = "1" ]; then
    grep -Eiv '^Co-Authored-By: Claude <noreply@anthropic\\.com>$' "$tmpfile" | \\
      grep -Ei 'Co-Authored-By:.*(Claude|Anthropic|GPT|OpenAI|Copilot|noreply@anthropic)' && return 1
  else
    grep -Ei 'Co-Authored-By:.*(Claude|Anthropic|GPT|OpenAI|Copilot|noreply@anthropic)' "$tmpfile" && return 1
  fi
  grep -Ei 'Generated (by|with).*(Claude|\\bAI\\b|GPT|OpenAI|Copilot)' "$tmpfile" && return 1
  grep -Ei '🤖.*(Claude|\\bAI\\b|GPT|OpenAI)' "$tmpfile" && return 1
  return 0
}

validate_msg "${msgFile}"
`;
  try {
    const result = spawnSync('bash', ['-c', script], {
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    return { status: result.status };
  } finally {
    rmSync(tmpDir, { recursive: true, force: true });
  }
}

// ═══════════════════════════════════════════════════
// Group A: Guard script regex tests (7 tests)
// ═══════════════════════════════════════════════════

test('A1: rejects Co-Authored-By Claude', () => {
  const r = runGuard('fix: something\n\nCo-Authored-By: Claude <noreply@anthropic.com>');
  assert.notEqual(r.status, 0, 'should reject Claude co-author');
  assert.ok(r.output.includes('AI attribution detected'), r.output);
});

test('A2: rejects Co-Authored-By Anthropic', () => {
  const r = runGuard('fix: something\n\nCo-Authored-By: Anthropic Bot <bot@anthropic.com>');
  assert.notEqual(r.status, 0, 'should reject Anthropic co-author');
});

test('A3: rejects Generated by Claude', () => {
  const r = runGuard('fix: something\n\nGenerated by Claude Code');
  assert.notEqual(r.status, 0, 'should reject Generated by Claude');
});

test('A4: rejects emoji robot AI tag', () => {
  const r = runGuard('fix: something\n\n\u{1F916} Claude assisted');
  assert.notEqual(r.status, 0, 'should reject robot emoji AI tag');
});

test('A5: passes human co-author', () => {
  const r = runGuard('fix: something\n\nCo-Authored-By: Jane Doe <jane@example.com>');
  assert.equal(r.status, 0, `human co-author should pass, got: ${r.output}`);
});

test('A6: passes clean commit message', () => {
  const r = runGuard('feat: Add user authentication\n\nImplements JWT-based auth flow.');
  assert.equal(r.status, 0, `clean message should pass, got: ${r.output}`);
});

test('A7: ALLOW_AI_COAUTHOR=1 bypasses all checks', () => {
  const r = runGuard(
    'fix: something\n\nCo-Authored-By: Claude <noreply@anthropic.com>',
    { ALLOW_AI_COAUTHOR: '1' }
  );
  assert.equal(r.status, 0, `ALLOW_AI_COAUTHOR should bypass, got: ${r.output}`);
});

// ═══════════════════════════════════════════════════
// Group B: validate_msg function tests (5 tests)
// ═══════════════════════════════════════════════════

test('B1: blocks AI co-author without --ai-co-author flag', () => {
  const r = runValidateMsg(
    'fix: something\n\nCo-Authored-By: Claude <noreply@anthropic.com>',
    false
  );
  assert.notEqual(r.status, 0, 'should block AI co-author without flag');
});

test('B2: allows exact Co-Authored-By format with --ai-co-author', () => {
  const r = runValidateMsg(
    'fix: something\n\nCo-Authored-By: Claude <noreply@anthropic.com>',
    true
  );
  assert.equal(r.status, 0, 'should allow exact format with flag');
});

test('B3: blocks variant Co-Authored-By format even with --ai-co-author', () => {
  const r = runValidateMsg(
    'fix: something\n\nCo-Authored-By: Claude Code <noreply@anthropic.com>',
    true
  );
  assert.notEqual(r.status, 0, 'should block variant format even with flag');
});

test('B4: blocks Generated-by even with --ai-co-author', () => {
  const r = runValidateMsg(
    'fix: something\n\nGenerated by Claude Code',
    true
  );
  assert.notEqual(r.status, 0, 'Generated-by should be blocked regardless of flag');
});

test('B5: blocks emoji tag even with --ai-co-author', () => {
  const r = runValidateMsg(
    'fix: something\n\n\u{1F916} Claude generated this',
    true
  );
  assert.notEqual(r.status, 0, 'emoji tag should be blocked regardless of flag');
});

// ═══════════════════════════════════════════════════
// Group C: Structural tests (3 tests)
// ═══════════════════════════════════════════════════

test('C1: commit-msg-guard.sh exists and is executable', () => {
  const stat = statSync(guardPath);
  assert.ok(stat.isFile(), 'guard script should be a file');
  assert.ok((stat.mode & 0o100) !== 0, 'guard script should be executable');
});

test('C2: missing commit message file exits with error', () => {
  const result = spawnSync('bash', [guardPath, '/tmp/nonexistent-file-12345'], {
    encoding: 'utf8',
    stdio: ['pipe', 'pipe', 'pipe'],
  });
  assert.notEqual(result.status, 0, 'missing file should exit non-zero');
});

test('C3: case-insensitive matching works', () => {
  const r = runGuard('fix: something\n\nco-authored-by: claude <noreply@anthropic.com>');
  assert.notEqual(r.status, 0, 'lowercase co-authored-by should still be caught');
});

// ═══════════════════════════════════════════════════
// Group D: ERE cross-platform tests (2 tests)
// ═══════════════════════════════════════════════════

test('D1: POSIX ERE alternation without backslash works', () => {
  // Verify the guard uses ERE (unescaped | for alternation)
  const r1 = runGuard('fix: something\n\nCo-Authored-By: GPT-4 <gpt@openai.com>');
  assert.notEqual(r1.status, 0, 'GPT alternation should match');

  const r2 = runGuard('fix: something\n\nCo-Authored-By: Copilot <copilot@github.com>');
  assert.notEqual(r2.status, 0, 'Copilot alternation should match');

  const r3 = runGuard('fix: something\n\nGenerated with AI tools');
  assert.notEqual(r3.status, 0, 'Generated with AI should match');
});

test('D2: POSIX ERE grouping without non-capturing syntax works', () => {
  // ERE uses (...) not (?:...) — verify patterns work correctly
  const r1 = runGuard('fix: something\n\nGenerated by Claude Code');
  assert.notEqual(r1.status, 0, 'Generated by should match');

  const r2 = runGuard('fix: something\n\nGenerated with GPT');
  assert.notEqual(r2.status, 0, 'Generated with should match');
});

// === deep-explore regression: \bAI\b must not false-positive; GPT stays unbounded ===
// The inline validate_msg above mirrors skills/smart-commit/references/execute-mode.md.
// \bAI\b passes ordinary words containing "ai" (maintainer/domain); GPT is unbounded
// so it still catches ChatGPT/GPT-4, and every pattern lists OpenAI explicitly.

test('validate_msg FP regression: "Generated by the maintainer" passes', () => {
  const r = runValidateMsg('docs: update\n\nGenerated by the maintainer script.\n');
  assert.equal(r.status, 0);
});

test('validate_msg FP regression: "Generated by domain tooling" passes', () => {
  const r = runValidateMsg('chore: regen\n\nGenerated by domain tooling.\n');
  assert.equal(r.status, 0);
});

test('validate_msg still blocks standalone "Generated by AI"', () => {
  const r = runValidateMsg('feat: x\n\nGenerated by AI assistant\n');
  assert.notEqual(r.status, 0);
});

test('validate_msg blocks "Generated with ChatGPT" (unbounded GPT)', () => {
  const r = runValidateMsg('feat: x\n\nGenerated with ChatGPT\n');
  assert.notEqual(r.status, 0);
});

test('validate_msg blocks "Generated by OpenAI" (explicit OpenAI)', () => {
  const r = runValidateMsg('feat: x\n\nGenerated by OpenAI Codex\n');
  assert.notEqual(r.status, 0);
});

test('validate_msg blocks robot emoji + ChatGPT', () => {
  const r = runValidateMsg('feat: x\n\n🤖 Generated with ChatGPT\n');
  assert.notEqual(r.status, 0);
});
