const { test } = require('node:test');
const assert = require('node:assert/strict');
const { resolve } = require('node:path');
const { statSync, writeFileSync, mkdtempSync, rmSync, mkdirSync, chmodSync } = require('node:fs');
const { spawnSync } = require('node:child_process');
const { tmpdir } = require('node:os');

const guardPath = resolve(__dirname, '../../scripts/commit-msg-guard.sh');

// Helper: run guard script with a message, return { status, output }
function runGuard(message, env = {}) {
  const tmpDir = mkdtempSync(resolve(tmpdir(), 'smart-commit-test-'));
  const msgFile = resolve(tmpDir, 'COMMIT_MSG');
  writeFileSync(msgFile, message);
  try {
    const result = spawnSync('bash', [guardPath, msgFile], {
      encoding: 'utf8',
      env: { ...process.env, ...env },
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    return {
      status: result.status,
      output: (result.stdout || '') + (result.stderr || ''),
    };
  } finally {
    rmSync(tmpDir, { recursive: true, force: true });
  }
}

// Helper: the runtime validation documented in execute-mode.md.
// It deliberately does NOT re-implement the policy: the doc specifies running
// scripts/commit-msg-guard.sh itself, so this helper runs exactly that. A copy
// here would be the drift that P2-c of the round-40 review found — the tests
// would have been checking their own copy, not the shipped instruction.
function runValidateMsg(message, aiCoAuthor = false) {
  return runGuard(message, aiCoAuthor ? { ALLOW_AI_COAUTHOR: '1' } : {});
}

// ═══════════════════════════════════════════════════
// Group A: Guard script regex tests (7 tests)
// ═══════════════════════════════════════════════════

test('A1: rejects Co-Authored-By Claude', () => {
  const r = runGuard('fix: something\n\nCo-Authored-By: Claude <noreply@anthropic.com>');
  assert.notEqual(r.status, 0, 'should reject Claude co-author');
  assert.ok(r.output.includes('AI attribution detected'), r.output);
});

test('A2: rejects Co-Authored-By Anthropic', () => {
  const r = runGuard('fix: something\n\nCo-Authored-By: Anthropic Bot <bot@anthropic.com>');
  assert.notEqual(r.status, 0, 'should reject Anthropic co-author');
});

test('A3: rejects Generated by Claude', () => {
  const r = runGuard('fix: something\n\nGenerated by Claude Code');
  assert.notEqual(r.status, 0, 'should reject Generated by Claude');
});

test('A4: rejects emoji robot AI tag', () => {
  const r = runGuard('fix: something\n\n\u{1F916} Claude assisted');
  assert.notEqual(r.status, 0, 'should reject robot emoji AI tag');
});

test('A5: passes human co-author', () => {
  const r = runGuard('fix: something\n\nCo-Authored-By: Jane Doe <jane@example.com>');
  assert.equal(r.status, 0, `human co-author should pass, got: ${r.output}`);
});

test('A6: passes clean commit message', () => {
  const r = runGuard('feat: Add user authentication\n\nImplements JWT-based auth flow.');
  assert.equal(r.status, 0, `clean message should pass, got: ${r.output}`);
});

test('A7: ALLOW_AI_COAUTHOR=1 permits the exact whitelisted line (narrow opt-in, not a bypass)', () => {
  const r = runGuard(
    'fix: something\n\nCo-Authored-By: Claude <noreply@anthropic.com>',
    { ALLOW_AI_COAUTHOR: '1' }
  );
  assert.equal(r.status, 0, `exact whitelisted line should pass, got: ${r.output}`);
});

// ═══════════════════════════════════════════════════
// Group B: runtime validation (execute-mode.md) — same script, whitelist path
// ═══════════════════════════════════════════════════

test('B1: blocks AI co-author without --ai-co-author flag', () => {
  const r = runValidateMsg(
    'fix: something\n\nCo-Authored-By: Claude <noreply@anthropic.com>',
    false
  );
  assert.notEqual(r.status, 0, 'should block AI co-author without flag');
});

test('B2: allows exact Co-Authored-By format with --ai-co-author', () => {
  const r = runValidateMsg(
    'fix: something\n\nCo-Authored-By: Claude <noreply@anthropic.com>',
    true
  );
  assert.equal(r.status, 0, 'should allow exact format with flag');
});

test('B3: blocks variant Co-Authored-By format even with --ai-co-author', () => {
  const r = runValidateMsg(
    'fix: something\n\nCo-Authored-By: Claude Code <noreply@anthropic.com>',
    true
  );
  assert.notEqual(r.status, 0, 'should block variant format even with flag');
});

test('B4: blocks Generated-by even with --ai-co-author', () => {
  const r = runValidateMsg(
    'fix: something\n\nGenerated by Claude Code',
    true
  );
  assert.notEqual(r.status, 0, 'Generated-by should be blocked regardless of flag');
});

test('B5: blocks emoji tag even with --ai-co-author', () => {
  const r = runValidateMsg(
    'fix: something\n\n\u{1F916} Claude generated this',
    true
  );
  assert.notEqual(r.status, 0, 'emoji tag should be blocked regardless of flag');
});

// ═══════════════════════════════════════════════════
// Group C: Structural tests (3 tests)
// ═══════════════════════════════════════════════════

test('C1: commit-msg-guard.sh exists and is executable', () => {
  const stat = statSync(guardPath);
  assert.ok(stat.isFile(), 'guard script should be a file');
  assert.ok((stat.mode & 0o100) !== 0, 'guard script should be executable');
});

test('C2: missing commit message file exits with error', () => {
  const result = spawnSync('bash', [guardPath, '/tmp/nonexistent-file-12345'], {
    encoding: 'utf8',
    stdio: ['pipe', 'pipe', 'pipe'],
  });
  assert.notEqual(result.status, 0, 'missing file should exit non-zero');
});

test('C3: case-insensitive matching works', () => {
  const r = runGuard('fix: something\n\nco-authored-by: claude <noreply@anthropic.com>');
  assert.notEqual(r.status, 0, 'lowercase co-authored-by should still be caught');
});

// ═══════════════════════════════════════════════════
// Group D: ERE cross-platform tests (2 tests)
// ═══════════════════════════════════════════════════

test('D1: POSIX ERE alternation without backslash works', () => {
  // Verify the guard uses ERE (unescaped | for alternation)
  const r1 = runGuard('fix: something\n\nCo-Authored-By: GPT-4 <gpt@openai.com>');
  assert.notEqual(r1.status, 0, 'GPT alternation should match');

  const r2 = runGuard('fix: something\n\nCo-Authored-By: Copilot <copilot@github.com>');
  assert.notEqual(r2.status, 0, 'Copilot alternation should match');

  const r3 = runGuard('fix: something\n\nGenerated with AI tools');
  assert.notEqual(r3.status, 0, 'Generated with AI should match');
});

test('D2: POSIX ERE grouping without non-capturing syntax works', () => {
  // ERE uses (...) not (?:...) — verify patterns work correctly
  const r1 = runGuard('fix: something\n\nGenerated by Claude Code');
  assert.notEqual(r1.status, 0, 'Generated by should match');

  const r2 = runGuard('fix: something\n\nGenerated with GPT');
  assert.notEqual(r2.status, 0, 'Generated with should match');
});

// === deep-explore regression: \bAI\b must not false-positive; GPT stays unbounded ===
// runValidateMsg above runs the guard, which is what execute-mode.md instructs.
// \bAI\b passes ordinary words containing "ai" (maintainer/domain); GPT is unbounded
// so it still catches ChatGPT/GPT-4, and every pattern lists OpenAI explicitly.

test('validate_msg FP regression: "Generated by the maintainer" passes', () => {
  const r = runValidateMsg('docs: update\n\nGenerated by the maintainer script.\n');
  assert.equal(r.status, 0);
});

test('validate_msg FP regression: "Generated by domain tooling" passes', () => {
  const r = runValidateMsg('chore: regen\n\nGenerated by domain tooling.\n');
  assert.equal(r.status, 0);
});

test('validate_msg still blocks standalone "Generated by AI"', () => {
  const r = runValidateMsg('feat: x\n\nGenerated by AI assistant\n');
  assert.notEqual(r.status, 0);
});

test('validate_msg blocks "Generated with ChatGPT" (unbounded GPT)', () => {
  const r = runValidateMsg('feat: x\n\nGenerated with ChatGPT\n');
  assert.notEqual(r.status, 0);
});

test('validate_msg blocks "Generated by OpenAI" (explicit OpenAI)', () => {
  const r = runValidateMsg('feat: x\n\nGenerated by OpenAI Codex\n');
  assert.notEqual(r.status, 0);
});

test('validate_msg blocks robot emoji + ChatGPT', () => {
  const r = runValidateMsg('feat: x\n\n🤖 Generated with ChatGPT\n');
  assert.notEqual(r.status, 0);
});

// ═══════════════════════════════════════════════════
// Group E: round-40 review findings
// ═══════════════════════════════════════════════════

const { readFileSync } = require('node:fs');
const execModePath = resolve(__dirname, '../../skills/smart-commit/references/execute-mode.md');
const skillPath = resolve(__dirname, '../../skills/smart-commit/SKILL.md');
const gitEnvPath = resolve(__dirname, '../../skills/smart-commit/references/git-environment.md');

// Round 48, P2: the policy prose moved into git-environment.md but no test read that file,
// so the "one canonical list" could drift from every copy of it and stay green. The prefix
// is therefore READ from the reference — the single source — and the other files must quote
// it byte-for-byte. Weakening the reference now fails here (the token check below); changing
// any copy without the reference fails wherever that copy is asserted.
const CANONICAL_PREFIX = (() => {
  const m = readFileSync(gitEnvPath, 'utf8').match(/^GIT_ENV="(env -u GIT_DIR[^"]*)"$/m);
  assert.ok(m, 'git-environment.md § 1 must declare the canonical GIT_ENV prefix');
  return m[1];
})();

// What the prefix must still cover, stated independently of the string above so that
// shortening the reference is caught rather than silently redefining "canonical".
const REQUIRED_ENV_TOKENS = [
  // repository / tree / index / object-store selection
  '-u GIT_DIR', '-u GIT_WORK_TREE', '-u GIT_COMMON_DIR', '-u GIT_INDEX_FILE',
  '-u GIT_OBJECT_DIRECTORY', '-u GIT_ALTERNATE_OBJECT_DIRECTORIES',
  '-u GIT_NAMESPACE', '-u GIT_CEILING_DIRECTORIES',
  // pathspec interpretation: `:(literal)` on each operand must be honoured, so every
  // variable that could reinterpret it is stripped — including GIT_LITERAL_PATHSPECS
  // itself, which would otherwise make the magic prefix part of the filename.
  '-u GIT_GLOB_PATHSPECS', '-u GIT_ICASE_PATHSPECS', '-u GIT_NOGLOB_PATHSPECS',
  '-u GIT_LITERAL_PATHSPECS',
  // Config injection and ancestry redirection. Added after the executor's scrub list was
  // re-derived from `git rev-parse --local-env-vars` and this prefix was found narrower:
  // GIT_CONFIG_PARAMETERS injects config process-wide, so Step 1c's identity diagnostic
  // (`git config --get user.email`) reports one identity while the commit records another —
  // a check whose only job is to be trustworthy, silently lying. The same channel reaches
  // core.hooksPath (disabling the commit-msg guard) and diff.external.
  '-u GIT_CONFIG', '-u GIT_CONFIG_PARAMETERS', '-u GIT_CONFIG_COUNT',
  '-u GIT_IMPLICIT_WORK_TREE', '-u GIT_PREFIX',
  // ancestry overlays: both redirect what `rev-list` treats as already reachable
  '-u GIT_GRAFT_FILE', '-u GIT_SHALLOW_FILE',
  '-u GIT_NO_REPLACE_OBJECTS', '-u GIT_REPLACE_REF_BASE',
  // the opt-in is stripped by default and re-added only as a trailing assignment
  '-u ALLOW_AI_COAUTHOR',
];

test('F1d: the canonical git environment is defined once and quoted identically everywhere', () => {
  for (const tok of REQUIRED_ENV_TOKENS) {
    assert.ok(CANONICAL_PREFIX.includes(tok),
      `the canonical prefix must still carry ${tok} — dropping it re-opens the defect it closes`);
  }
  // Round 49, P2: asserting mere PRESENCE let a file with two independent assignments keep
  // one canonical copy while the other was shortened — execute-mode.md has exactly that
  // shape, and Codex's mutant of its post-commit fence stayed green. Every assignment in
  // every file is compared, and each file must have at least one so the loop cannot pass
  // by matching nothing.
  const hardeningSpec = resolve(__dirname, '../../docs/features/smart-commit-hardening/2-tech-spec.md');
  // execute-mode.md is deliberately absent from THIS sweep: `--execute` no longer assembles
  // the prefix in Markdown, it runs a script that unsets the same list process-wide, and F1b
  // asserts that equivalence rather than letting the file drop out. Its one remaining literal
  // copy — the paste-ready recovery commands — is covered by F1f, not by matching nothing here.
  for (const [path, label] of [
    [skillPath, 'SKILL.md'],
    [gitEnvPath, 'git-environment.md'], [hardeningSpec, 'smart-commit-hardening/2-tech-spec.md'],
  ]) {
    const found = readFileSync(path, 'utf8').match(/GIT_ENV="[^"]*"/g) || [];
    assert.ok(found.length >= 1, `${label} must declare the prefix at least once`);
    for (const decl of found) {
      assert.equal(decl, `GIT_ENV="${CANONICAL_PREFIX}"`,
        `${label} must quote the canonical prefix byte-for-byte in every assignment`);
    }
  }
  // `-C "$REPO_ROOT"` is half the contract; the reference must carry it too, or the
  // per-fence assertions below would be enforcing a rule stated nowhere.
  assert.match(readFileSync(gitEnvPath, 'utf8'), /REPO_ROOT=\$\(\$GIT_ENV git rev-parse --show-toplevel && printf \.\) \|\| \{[^}]*\}\nREPO_ROOT=\$\{REPO_ROOT%\.\}; REPO_ROOT=\$\{REPO_ROOT%\$'\\n'\}/,
    'the reference must define how REPO_ROOT is derived');
  assert.match(readFileSync(gitEnvPath, 'utf8'), /\$GIT_ENV git -C "\$REPO_ROOT"/,
    'and that every command is pinned to it');
});

/**
 * The exact copyable inventory of § On a leak, outside the two blocks pinned separately.
 *
 * Generated from the document, then frozen. Adding a fenced block or an inline code span to the
 * section fails this list until it is added here — which is the point: the author states what
 * the new span is, instead of a classifier guessing. The two templates are included whole
 * because a command pasted out of a template is copyable exactly like one pasted out of a code
 * block; the § Recovery commands block and the `<PREFIX>` definition are excluded here only
 * because F1f pins them line-by-line under stricter rules.
 */
const PINNED_COPYABLE = [
  '❌ AI attribution leaked in commit <sha> (= HEAD). Remaining commit groups ABORTED.\n'
  + '   The guard reported the offending line numbers above (content withheld).\n'
  + '   To fix (manual): run [amend] from § Recovery commands.\n'
  + '   To prevent: /install-scripts commit-msg-guard, then cp .claude/scripts/commit-msg-guard.sh <hooks-path>/commit-msg\n',
  '❌ AI attribution leaked in commit <sha>, which is NOT HEAD. Remaining commit groups ABORTED.\n'
  + '   Amending would rewrite a different commit and leave this one as it is.\n'
  + '   Where it lives: run [where-1] and [where-2] from § Recovery commands.\n'
  + '   Inspect it first; the correct repair depends on what references it.\n',
  'commit',
  'verify-last',
  // The one git command named outside the recovery block: prose naming the operation, with no
  // prefix, no -C and no target. It is not an instruction to run anything.
  'git commit --amend',
  'post-commit',
  'a graft installed by the POST-commit hook is refused, not traversed through',
  '--amend',
  'env -u …',
  "-C '<REPO_ROOT>'",
  'GIT_DIR',
  '--amend',
  '<PREFIX>',
  'git-environment.md',
  '$GIT_ENV',
  '<sha>',
  // The comparison the amend branch is taken on — prefixed and -C pinned like the rest.
  "<PREFIX> git -C '<REPO_ROOT>' rev-parse HEAD",
];

/**
 * Everything a reader could paste out of § On a leak, minus the two blocks pinned separately,
 * plus what is wrong with it.
 *
 * A function rather than assertions inlined in F1f, so F1k can run the SAME extractor against a
 * bypass. Every previous version of this rule was asserted inline and had no control at all,
 * which is exactly how four successive selectors shipped while unable to see the constructs
 * they were named after.
 *
 * What it does NOT do any more is classify. Five selectors tried, each wrong in a new way, and
 * the fifth — "one word is a reference, two or more is an invocation" — was unsound on its face:
 * with `GIT='git show HEAD'` the one-word span `$GIT` executes that command, and `env $GIT show
 * HEAD` puts the expansion in the second position where nothing looked (Codex, round 95, both
 * confirmed running here). Every such rule admits the form it did not anticipate.
 *
 * So the surface is ENUMERATED instead. F1f pins the exact inline spans and fenced blocks the
 * section may contain; anything new fails until it is added deliberately, whatever it is spelled
 * like. That is complete by construction — there is no inference left to be wrong — and it is
 * the same discipline `PINNED_CODE_BEARING` applies to the scripts. `problems` therefore carries
 * only what the pin cannot see: surfaces the extractor does not reach at all.
 */
function copyableSurface(section) {
  const outside = section
    .replace(/### Recovery commands[\s\S]*?```\n[\s\S]*?```/, '')
    .replace(/`<PREFIX>` is:\n\n```bash\n[^\n]*\n```/, '');
  // Code spans are read from text with fenced blocks REMOVED, because a span may cross a line
  // ending and a line-crossing pattern run over the raw section would let one span swallow a
  // whole fence. Round 97, Codex P2: `[^`\n]+` could not see a wrapped span at all —
  // `` `git\nshow HEAD` `` renders as inline code, pastes as one command, and left the pinned
  // inventory byte-identical. This document already contains one such span (in § What this
  // cannot do), so the construct is not hypothetical here either.
  const spanText = outside.replace(/^ {0,3}(`{3,}|~{3,})[^\n]*\n[\s\S]*?^ {0,3}\1[^\n]*$/gm, '');
  const copyable = [
    // Info string `[^\n]*`, not `[a-z]*`: a ```shell-session block was skipped WHOLE by the
    // latter, taking whatever it contained off the surface the rule governs (Codex, round 94).
    ...[...outside.matchAll(/```[^\n]*\n([\s\S]*?)```/g)].map((m) => m[1]),
    ...[...spanText.matchAll(/`([^`]+)`/g)]
      .map((m) => m[1])
      // A code span may not contain a blank line: a backtick pair straddling one is two
      // unrelated spans, not a single long one.
      .filter((s) => !/\n[ \t]*\n/.test(s))
      // Line continuations joined first — `g\` + newline + `it --version` is ONE word to the
      // shell — then CommonMark's own rule, which renders a line ending inside a span as a space.
      .map((s) => s.replace(/\\\n/g, '').replace(/\n/g, ' ')),
  ].map((s) => s.replace(/\\\n/g, ''));

  // Surfaces the two extractors cannot reach at all. An enumerated pin is only as complete as
  // the set of surfaces feeding it, and CommonMark has more code surfaces than a pair of regexes
  // covers — Codex injected a tab-indented block and a raw `<pre><code>` in round 96 and BOTH
  // left `copyable` byte-identical to the pin. Each is banned by FORM rather than parsed, which
  // is the same restricted-subset move the heredoc rule makes: cheap, fail-closed, and stated.
  const problems = [];
  const banned = [
    [/~~~/, 'a ~~~ fence is copyable and unextracted'],
    [/\t/, 'a tab makes an indented code block (and is invisible in review)'],
    [/<(pre|code|xmp|plaintext)\b/i, 'raw HTML renders a code surface the extractors do not see'],
    // Two or more backticks open a code span with a longer delimiter, which the single-backtick
    // extractor reads as an empty span and skips past; four or more open a fence the three-
    // backtick pairing mis-pairs. Both are legal CommonMark and neither is needed here.
    [/(^|[^`])``(?!`)/m, 'a multi-backtick code span is not extracted'],
    [/^`{4,}/m, 'a fence longer than three backticks is not extracted'],
    // A container measures indentation from INSIDE itself, so a blockquote marker plus four
    // spaces is an indented code block whose first character is `>` — invisible to the column-0
    // scan below, which is the second half of round 97's P2. Lists need no rule of their own:
    // that scan flags any line indented four spaces, container-relative or not.
    [/^ {0,3}>+ {4,}\S/m, 'a blockquote can carry an indented code block the column-0 check misses'],
  ];
  for (const [re, why] of banned) if (re.test(outside)) problems.push(why);
  // A line indented four spaces outside a fence is a CommonMark indented code block: rendered
  // as copyable code, and matched by neither extractor above.
  let inFence = false;
  for (const line of outside.split('\n')) {
    if (/^ *```/.test(line)) { inFence = !inFence; continue; }
    if (!inFence && /^ {4,}\S/.test(line)) problems.push(`indented code block: ${line.trim()}`);
  }
  // An unclosed fence would make the last extractor pair swallow the rest of the section, so the
  // count is checked rather than assumed.
  if ((outside.match(/^ *```/gm) || []).length % 2 !== 0) problems.push('an unclosed fence');
  return { problems, copyable, outside };
}

test('F1f: the leak-recovery commands users are told to paste carry the canonical prefix', () => {
  // Round 86, Codex P2. § On a leak writes the prefix out LITERALLY — the user's shell has no
  // `$GIT_ENV` — so it is a second copy that F1d's `GIT_ENV="…"` sweep cannot see. It was
  // byte-identical when written and nothing kept it that way. That matters more here than in
  // an ordinary example: these commands run against a repository that has just been shown to
  // contain a leaked commit, and an inherited GIT_DIR points them at a different one.
  const src = readFileSync(execModePath, 'utf8');
  const fence = src.match(/`<PREFIX>` is:\n\n```bash\n([^\n]*)\n```/);
  assert.ok(fence, 'execute-mode.md must still define <PREFIX> in a fenced block');
  assert.equal(fence[1], CANONICAL_PREFIX,
    'and it must be the canonical prefix byte-for-byte — this copy is what the user pastes');

  // Rounds 87 and 88, Codex P2 twice. Two failed selectors first: `^ *<PREFIX>` could only ever
  // find lines that already complied, and indent-inside-a-fence was presentation — an
  // unindented fence, or a ```bash one, slipped straight past. Both times the test's NAME
  // claimed a completeness its selector could not deliver.
  //
  // So the document changed instead of the selector. § Recovery commands is now the one place a
  // paste-ready command may appear, and EVERY line of that block is checked — no selection step
  // remains to be wrong. What used to be a guess is now a property of the document.
  const section = src.slice(src.indexOf('## On a leak'));
  const block = section.match(/### Recovery commands[\s\S]*?```\n([\s\S]*?)```/);
  assert.ok(block, 'the § Recovery commands block must exist — it is where the contract lives');
  const cmds = block[1].split('\n').filter((l) => l.trim());
  assert.ok(cmds.length >= 3, `the block must still carry its commands; saw ${cmds.length}`);
  // Round 89, Codex P2: the label used to LEAD the line, which made the block's own "paste-ready"
  // claim false — `[amend]` is a command word, and `/bin/bash -c '[amend] true'` exits 127 with
  // "command not found", measured. It is a trailing comment now, so the line survives a paste.
  const defined = cmds.map((cmd) => {
    const m = cmd.match(/^<PREFIX> git -C '<REPO_ROOT>' \S.*?\s+# \[([a-z0-9-]+)\]$/);
    assert.ok(m, `every line of the recovery block must be a pinned command labelled by a trailing comment: ${cmd}`);
    return m[1];
  });
  assert.deepEqual(defined, [...new Set(defined)],
    `recovery labels must be unique — a duplicate makes "run [amend]" ambiguous: ${defined}`);

  // And the other half of the contract: no command may be spelled out anywhere ELSE in the
  // section. This is what makes "every line of that block" equal to "every recovery command" —
  // without it, the block could be complete and a bare `git show <sha>` could still sit in a
  // template, unpinned and exposed to an inherited GIT_DIR.
  //
  // FIVE selectors have failed here, each narrower than the claim above it. `^ *<PREFIX>` only
  // found lines that already complied. A line-start anchor missed a table cell (`| Inspect |
  // `git show <sha>` |`, which starts with `|`) and an `env -u GIT_DIR git show <sha>` line
  // (which starts with `env`). Keying on the OPERAND missed `git show HEAD`. Banning characters
  // across the whole span rejected prose for naming a variable while `$GIT status` walked
  // through. Classifying by token count admitted one-word `$GIT`, which executes whatever the
  // variable holds. Codex reproduced every one of them.
  //
  // The common shape: each tried to DECIDE whether a span was a command. So the sixth does not
  // decide — it enumerates. The copyable inventory is pinned exactly, and anything new fails
  // until an author adds it deliberately. There is no spelling left for a rule to miss, because
  // there is no rule; `problems` covers only the surfaces the extractor cannot reach at all.
  const { problems, copyable, outside } = copyableSurface(section);
  assert.deepEqual(problems, [],
    `the section must expose no copyable surface the pin cannot see: ${problems}`);
  assert.deepEqual(copyable, PINNED_COPYABLE,
    'the copyable inventory of § On a leak is pinned — add new spans to PINNED_COPYABLE deliberately');

  // Referenced and defined must be the SAME set, not one contained in the other. Containment in
  // either direction hides a real defect: an unreferenced definition is a command nothing sends
  // users to, and an undefined reference sends them to a command that is not there.
  const referenced = (outside.match(/\[([a-z0-9-]+)\](?! *[(:])/g) || [])
    .map((l) => l.slice(1, -1));
  assert.deepEqual([...new Set(referenced)].sort(), [...defined].sort(),
    'the templates and the recovery block must name exactly the same labels');
});

test('F1k: F1f mutation control — every bypass is seen, and documentation still passes', () => {
  // F1f had no control at all until now, and that is the whole story of rounds 87 through 95:
  // five selectors shipped in a row, each unable to see the construct its own name promised to
  // catch, because nothing ever ran a bypass through it. Each case below was reproduced against
  // this document before being written down.
  const src = readFileSync(execModePath, 'utf8');
  const section = src.slice(src.indexOf('## On a leak'));
  const anchor = '`git commit --amend`';
  assert.ok(section.includes(anchor), 'the mutation anchor must exist in the section');
  // "Seen" is the pin disagreeing, or a surface the pin cannot reach. With an enumerated
  // inventory these are the only two ways anything can change.
  const seen = (mutant) => {
    const s = copyableSurface(mutant);
    return s.problems.length > 0
      || JSON.stringify(s.copyable) !== JSON.stringify(PINNED_COPYABLE);
  };
  assert.equal(seen(section), false,
    'the shipped section must be clean — otherwise nothing below means anything');

  for (const [label, inject] of [
    // Computed command names with two or more words — invisible to the character ban that
    // preceded this, because neither carries `${` or `$(`.
    ['bare $GIT', '`$GIT status`'],
    ['quoted "$GIT"', '`"$GIT" status`'],
    ['single-quoted name', "`'git' status`"],
    // ONE word, and it executes: with GIT='git show HEAD', copying `$GIT` runs that command.
    // This is the form the token-count classifier waved through (Codex, round 95, confirmed).
    ['one-word $GIT', '`$GIT`'],
    // The expansion in second position, where a first-word rule never looked.
    ['expansion after env', '`env $GIT show HEAD`'],
    ['expansion after if', '`if $GIT status; then :; fi`'],
    // Fence syntaxes and info strings the extractor used to skip whole.
    ['~~~ fence', '~~~bash\ngit show HEAD\n~~~'],
    ['shell-session info string', '```shell-session\n$ git show HEAD\n```'],
    // A four-space indented block is CommonMark code, rendered copyable, matched by neither
    // extractor — so it is reported as an unreachable surface rather than scanned.
    ['indented code block', '    git show HEAD'],
    // A leading TAB is an indented code block just as four spaces are, and it is invisible in
    // review. Codex injected both in round 96 and each left the inventory byte-identical.
    ['tab-indented code block', '\tgit show HEAD'],
    // Raw HTML renders a code surface neither extractor reaches.
    ['raw HTML pre/code', '<pre><code>git show HEAD</code></pre>'],
    // A two-backtick span: the single-backtick extractor reads it as empty and skips past.
    ['multi-backtick code span', '``git show HEAD``'],
    // A four-backtick fence mis-pairs against the three-backtick pairing.
    ['four-backtick fence', '````\ngit show HEAD\n````'],
    // Splicing across a line continuation — one word to the shell, two lines to a splitter.
    ['line-continuation splice', '```bash\ng\\\nit show HEAD\n```'],
    // A code span may cross a line ending; CommonMark renders the break as a space, so this
    // pastes as one command. The `[^`\n]+` extractor could not match it at all (Codex, r97).
    ['wrapped code span', '`git\nshow HEAD`'],
    // Container-relative indentation: measured from inside the blockquote, this is an indented
    // code block, but its first character is `>` so a column-0 scan never sees four spaces.
    ['blockquote indented code', '> \n>     git show HEAD\n'],
    // CommonMark allows a fence opener up to three spaces in. SKILL.md already contains two,
    // which is how this was confirmed rather than assumed.
    ['indented fence', '   ```bash\n   git show HEAD\n   ```'],
    // And the plain unpinned invocation the whole rule exists for, with no trickery at all.
    ['unprefixed git', '`git show HEAD`'],
  ]) {
    // Function replacement, not a string: `$'`, `` $` ``, `$&` and `$n` are all substitution
    // patterns in a replacement STRING, so a payload containing one is silently rewritten into
    // something else. The mutant still differs from the source, so a bare `notEqual` reports a
    // bypass that was never actually injected — measured on this suite in round 97.
    const mutated = section.replace(anchor, () => `${anchor}\n\n${inject}\n`);
    assert.equal(mutated.includes(inject), true,
      `the ${label} mutation must apply VERBATIM — otherwise F1f proves nothing`);
    assert.equal(seen(mutated), true, `F1f must see the ${label} bypass`);
  }

  // The other direction, and it is not decoration: the version this replaces rejected a prose
  // span for NAMING a variable, and a `$ ` shell-session prompt for beginning with a `$`. A
  // check that fires on documentation teaches its reader to route around it, which is how a
  // real hole stays open behind a green test. Under an enumerated pin these pass for a
  // structural reason — they are prose, not copyable spans — rather than by being classified.
  for (const [label, inject] of [
    ['a variable named in prose', 'the ${GIT_DIR} variable is inherited'],
    ['a single-token reference', 'see $GIT_ENV and git-environment.md'],
    ['ordinary explanatory prose', 'The prefix pins the repository before anything is read.'],
  ]) {
    const mutated = section.replace(anchor, `${anchor}\n\n${inject}\n`);
    assert.notEqual(mutated, section, `the ${label} control must apply`);
    assert.equal(seen(mutated), false, `${label} is documentation, not a command — it must pass`);
  }
});

test('F1e: the shipped prefix actually runs — env stops parsing options at an assignment', () => {
  // Round 49, P1. The prefix briefly ended in `GIT_LITERAL_PATHSPECS=1`, and the default
  // branches appended `-u ALLOW_AI_COAUTHOR` after it. BSD env treats everything after the
  // first assignment as the command, so it tried to EXECUTE `-u` and exited 127: `--execute`
  // could not commit at all. Every previous oracle was textual and stayed green. This one
  // runs the shipped string, which is the only kind that could have caught it.
  const ok = spawnSync('/bin/sh', ['-c', `${CANONICAL_PREFIX} true`], { encoding: 'utf8' });
  assert.equal(ok.status, 0,
    `the canonical prefix must be executable as written; got ${ok.status}: ${ok.stderr}`);
  assert.ok(!/=/.test(CANONICAL_PREFIX.replace(/^env /, '')),
    'the prefix must contain no assignment — a later -u would be taken as the command');

  // The opt-in form: assignment AFTER the flags, and it must survive the earlier -u.
  const optIn = spawnSync('/bin/sh',
    ['-c', `${CANONICAL_PREFIX} ALLOW_AI_COAUTHOR=1 sh -c 'printf %s "$ALLOW_AI_COAUTHOR"'`],
    { encoding: 'utf8', env: { ...process.env, ALLOW_AI_COAUTHOR: '' } });
  assert.equal(optIn.stdout, '1', 'a trailing assignment must win over the prefix -u');
  // …and the default form really does strip a caller-supplied opt-in.
  const stripped = spawnSync('/bin/sh',
    ['-c', `${CANONICAL_PREFIX} sh -c 'printf %s "\${ALLOW_AI_COAUTHOR-unset}"'`],
    { encoding: 'utf8', env: { ...process.env, ALLOW_AI_COAUTHOR: '1' } });
  assert.equal(stripped.stdout, 'unset', 'the default form must strip an inherited opt-in');
});

// Round 83. Two independent lists claim to be the same list: the printed/inline `GIT_ENV`
// prefix and the `unset` block inside smart-commit-execute.sh. git-environment.md § 1 and
// F1b both use the word "identical", and until now nothing checked it — REQUIRED_ENV_TOKENS
// pins a FLOOR under each side separately, so either could grow past the other and stay
// green while the docs asserted equality. Set equality is the claim, so set equality is the
// test. Compared as sets, not strings, because the two are formatted differently by
// necessity (`-u X` versus a backslash-continued word list) and order carries no meaning.
test('F1i: the GIT_ENV prefix and the executor unset block are the same set of variables', () => {
  const prefixVars = new Set(
    [...CANONICAL_PREFIX.matchAll(/-u (\w+)/g)].map((m) => m[1]));
  const execSrc = readFileSync(
    resolve(__dirname, '../../skills/smart-commit/scripts/smart-commit-execute.sh'), 'utf8');
  const block = execSrc.match(/^unset GIT_DIR[\s\S]*?ALLOW_AI_COAUTHOR$/m);
  assert.ok(block, 'smart-commit-execute.sh must declare the scrub list as one unset block');
  const unsetVars = new Set(block[0].replace(/^unset /, '').replace(/\\\n\s*/g, ' ').split(/\s+/));

  assert.ok(prefixVars.size > 15, `sanity: the prefix must parse to a real list, got ${prefixVars.size}`);
  assert.deepEqual([...prefixVars].sort(), [...unsetVars].sort(),
    'git-environment.md § 1 calls these identical — they must actually be identical');
});

// The same list is also claimed to be DERIVED from git rather than hand-picked. That claim
// is checked against git itself, so a future Git that adds a local-env var fails here instead
// of silently leaving a hole (which is exactly how GIT_GRAFT_FILE and GIT_CONFIG_PARAMETERS
// were missed for 80 rounds).
test('F1j: the scrub list covers everything git rev-parse --local-env-vars names', () => {
  const named = spawnSync('git', ['rev-parse', '--local-env-vars'], { encoding: 'utf8' });
  assert.equal(named.status, 0, 'git must be able to report its own local env vars');
  const wanted = named.stdout.split('\n').map((s) => s.trim()).filter(Boolean);
  assert.ok(wanted.length >= 8, `sanity: git named only ${wanted.length} variables`);
  const prefixVars = new Set(
    [...CANONICAL_PREFIX.matchAll(/-u (\w+)/g)].map((m) => m[1]));
  const missing = wanted.filter((v) => !prefixVars.has(v));
  assert.deepEqual(missing, [],
    `git names these local-env vars that the prefix does not strip: ${missing.join(', ')}`);
});

// P1-a: the category is literally named "Co-Authored-By AI", but a bare `AI` matched
// none of the three patterns — only `Generated by` and the 🤖 tag were \bAI\b-bounded.
test('E1: Co-Authored-By with a bare AI name is rejected', () => {
  const r = runGuard('feat: x\n\nCo-Authored-By: AI Assistant <ai@example.com>');
  assert.notEqual(r.status, 0, `bare AI co-author must be rejected, got: ${r.output}`);
});

test('E2: Co-Authored-By: AI <...> alone is rejected', () => {
  const r = runGuard('feat: x\n\nCo-Authored-By: AI <bot@example.com>');
  assert.notEqual(r.status, 0, 'standalone AI co-author must be rejected');
});

test('E3: \\bAI\\b does not fire inside an ordinary name ("Kai")', () => {
  const r = runGuard('feat: x\n\nCo-Authored-By: Kai Nakamura <kai@example.com>');
  assert.equal(r.status, 0, `word-boundary must spare "Kai", got: ${r.output}`);
});

// Accepted trade-offs, asserted so they are a decision rather than a surprise. Each is
// fail-CLOSED: a rejected commit is reworded, an accepted AI trailer is not recoverable.
test('E4: accepted FP — a human co-author literally named "Ai" is rejected', () => {
  const r = runGuard('feat: x\n\nCo-Authored-By: Ai Wei <ai.wei@example.com>');
  assert.notEqual(r.status, 0, 'documented trade-off of the \\bAI\\b bound in Co-Authored-By');
});

test('E5: accepted FP — "Generated by Codex Pharmaceuticals" is rejected', () => {
  const r = runGuard('chore: migrate\n\nGenerated by Codex Pharmaceuticals migration tooling\n');
  assert.notEqual(r.status, 0, 'Codex is unbounded on purpose; documented trade-off');
});

test('E6: accepted FP — a human co-author named "Gemini" is rejected', () => {
  const r = runGuard('feat: x\n\nCo-Authored-By: Gemini Jones <gemini.jones@example.com>');
  assert.notEqual(r.status, 0, 'Gemini is unbounded on purpose; documented trade-off');
});

// P2-c: the previous version of this file re-implemented the validator, so a divergence
// between execute-mode.md and the guard was undetectable. These assert the duplication
// is gone rather than that the two copies happen to agree.
// Scoped to fenced bash blocks on purpose: these documents DESCRIBE the constructs
// they forbid, so a whole-file scan flags the prose that explains the fix. That exact
// mistake (a structural test matching its own explanatory comment) is why this helper
// exists rather than a substring check over the raw file.
/**
 * Every fenced block, as `{ info, body }`, honouring CommonMark's run-length rule: a fence closes
 * only on a run at least as long as its opener. A four-backtick block holding a markdown example
 * is therefore one block, and its body is re-scanned, because the three-backtick fences inside it
 * are exactly what a reader copies.
 */
function fencedBlocks(text) {
  const lines = text.split('\n');
  const out = [];
  for (let i = 0; i < lines.length;) {
    // Round 97, Codex P2: the opener was anchored at column 0 and to backticks alone, while
    // CommonMark also accepts up to three spaces of indentation and a `~~~` delimiter. Both
    // render as code and both are copyable, so moving a fixed-`EOF` heredoc into ```` ```bash ````
    // indented by two spaces, or into `~~~bash`, handed E10/E12 an empty string to scan. The
    // helper's name claimed CommonMark coverage; only the recognizer was narrower.
    const open = /^( {0,3})(`{3,}|~{3,})(.*)$/.exec(lines[i]);
    // A backtick fence's info string may not itself contain a backtick (a tilde fence's may).
    if (!open || (open[2][0] === '`' && open[3].includes('`'))) { i++; continue; }
    const indent = open[1].length;
    const strip = new RegExp(`^ {0,${indent}}`);
    const body = [];
    for (i++; i < lines.length; i++) {
      const close = /^ {0,3}(`{3,}|~{3,})[ \t]*$/.exec(lines[i]);
      // Same delimiter CHARACTER as well as at least the same run length: `~~~` does not close a
      // ```` ``` ```` block, so a tilde run inside a backtick fence is content, not a terminator.
      if (close && close[1][0] === open[2][0] && close[1].length >= open[2].length) break;
      // A fenced block's content is de-indented by the opener's own indentation, so an indented
      // fence yields the same body text as an unindented one.
      body.push(lines[i].replace(strip, ''));
    }
    i++;
    const block = { info: open[3].trim(), body: body.join('\n') };
    out.push(block);
    if (!/^(bash|sh|shell)\b/.test(block.info)) out.push(...fencedBlocks(block.body));
  }
  return out;
}

/**
 * The bash a reader can copy out of `path`.
 *
 * Classified by the FIRST word of the info string, not by an exact match on it. `^```bash\n`
 * accepted only that spelling, so ```` ```bash title=manual ```` still rendered as a bash block
 * and still copied, while disappearing from every check built on this helper — Codex moved a
 * fixed-`EOF` heredoc into one in round 96 and E10 went right past it.
 *
 * Scoped to fenced blocks on purpose: these documents DESCRIBE the constructs they forbid, so a
 * whole-file scan flags the prose explaining the fix. That exact mistake — a structural test
 * matching its own explanatory comment — is why this helper exists rather than a substring check.
 */
function bashBlocks(path) {
  return fencedBlocks(readFileSync(path, 'utf8'))
    .filter((b) => /^(bash|sh|shell)\b/.test(b.info))
    .map((b) => b.body)
    .join('\n');
}

// Round 76, P2. Two separate oracle defects had one root: they read PHYSICAL TEXT where they
// meant executable syntax. Both verified against this repository's own shape.
//   (a) A `#`-commented allocation satisfied both allocation oracles while the line that really
//       ran produced a fixed, predictable path — the exact property F3 exists to forbid, passing
//       because the evidence for it was in a comment.
//   (b) A line continuation splits `/bin/bash -p \` from `"$GUARD"`, so a site with no `--` was
//       not enumerated at all. It did not fail — it vanished, and `every()` over the remaining
//       sites stayed true. That is the round-75 finding again, one representation lower down.
// Comment-only lines go first, then continuations are joined, so a comment can never absorb the
// command below it.
const liveCode = (src) => src
  .split('\n').filter((l) => !/^\s*#/.test(l)).join('\n')
  .replace(/\s*\\\n\s*/g, ' ');   // the whitespace on BOTH sides collapses, or `rm \` + `-f`
                                  // rejoins as `rm  -f` and a single-space matcher misses it
                                  // again — the same disappearance one layer down

test('E7: execute-mode.md carries no second copy of the pattern table', () => {
  const code = bashBlocks(execModePath);
  assert.ok(code.length > 0, 'expected at least one bash block to inspect');
  assert.ok(!/grep -Ei '(Co-Authored-By|Generated\[|🤖)/.test(code),
    'execute-mode.md must not re-implement the patterns — it must run the guard');
});

test('E8: execute-mode.md does not strip the whitelist case-insensitively', () => {
  const code = bashBlocks(execModePath);
  assert.ok(!code.includes('grep -Eiv'),
    'a -Eiv whitelist strip disagrees with the guard\'s byte-exact grep -Fxv');
});

// P1-e: a fixed EOF delimiter is injectable — a message line equal to it ends the heredoc
// and the remainder is read as shell. create-pr prohibits the same construct.
// The oracle E10 applies, named so E11 can apply the SAME function to a mutant rather
// than re-asserting the mutation it just made — which proves only that replace() works.
//
// The delimiter is read the way the shell reads it, not matched as one literal spelling. The
// oracle used to be `!code.includes("<<'EOF'")`, which is a single quoting form: `<<EOF`,
// `<<"EOF"` and `<<\EOF` all terminate on the very same `EOF` line and all passed a test named
// "no fixed-EOF heredoc" (Codex). Quoting the delimiter changes whether the BODY expands — it
// never changes what ends the document, so it cannot be what the check keys on.
// That alternation was still one spelling short of the shell, and quote removal is why. Bash
// strips quoting across the WHOLE delimiter word, component by component, so `<<E"OF"`,
// `<<'E'OF`, `<<\E\O\F` and `<<$'EOF'` all terminate on a plain `EOF` line — measured under bash
// 3.2.57, each running the line after the `EOF`, while the alternation reported `E`, `E`, `E`
// and nothing (Codex, round 94). `<<EOF'` is NOT one of them: an unterminated single quote is a
// syntax error there. It is kept below as a spelling to reject on FORM, not as an evasion that
// runs — an earlier version of this comment offered it as a correction to the fourth example,
// which was a misreading: the fourth example was `<<$'EOF'`, and that one does run.
// Matching one component of a word the shell reads as a whole cannot be made complete by adding
// components; there is always another way to split it.
//
// So the same inversion the executor's oracles took in round 89: these blocks may use ONE
// heredoc spelling, and the check first enforces the spelling and only then resolves it. A
// canonical opener is `<<'NAME'` or `<<-'NAME'` with an uppercase name — fully single-quoted,
// so no component is left for quote removal to rejoin. Everything else is rejected as a
// spelling, without needing to know what it would resolve to. `<<<` is a here-string, not a
// heredoc: it has no terminator line, so nothing in a message can close it.
// The lookahead is load-bearing, and its absence is the same bug one level up: without it
// `<<'E'OF` matches the prefix `<<'E'`, resolves to the harmless name `E`, and the trailing
// `OF` — which the shell rejoins into `EOF` — is simply not looked at. A canonical opener must
// consume the WHOLE delimiter word, so what follows the closing quote has to end it.
//
// `<` and `>` belong in that set: bash accepts a redirection directly against the delimiter, as
// in `cat <<'SAFE'>out`, and without them a legitimate canonical heredoc was rejected (Codex,
// round 95, confirmed running here).
const CANONICAL_HEREDOC = /^<<-?'([A-Z][A-Z0-9_]*)'(?=[\s;|&)<>]|$)/;

/**
 * Every `<<` in the block, as `{ ok, name }` — `ok:false` for anything that is not a canonical
 * opener.
 *
 * Every `<<`, not every heredoc OPERATOR, and that is a deliberate over-reach rather than an
 * oversight. Telling the two apart needs quote-, comment- and arithmetic-aware lexing: `printf
 * '%s\n' "<<EOF"`, a trailing `# … <<EOF`, and `(( mask = value << 2 ))` all contain the
 * characters and open nothing (Codex, round 95). Writing that lexer inside a documentation test
 * is how the executor's oracles ended up needing eleven rounds of repair.
 *
 * So the subset is stated instead of inferred: **a bash block in these documents may not contain
 * `<<` except as a canonical heredoc opener.** It fails closed, it costs nothing today — no such
 * construct exists in either file — and if one is ever needed the block gets restructured or the
 * rule gets a lexer, deliberately. What it must not do is fail closed *silently*, so the
 * assertion below names the policy rather than reporting a mystery.
 */
const heredocOpeners = (code) => {
  const found = [];
  // Whole-line comments still go first: a line that exists only to discuss the construct is the
  // one false alarm certain to happen, in the very files that document it.
  const live = liveCode(code);
  for (let i = live.indexOf('<<'); i >= 0; i = live.indexOf('<<', i + 2)) {
    if (live[i + 2] === '<') { i += 1; continue; }   // here-string
    const m = CANONICAL_HEREDOC.exec(live.slice(i));
    found.push(m ? { ok: true, name: m[1] } : { ok: false, name: live.slice(i, i + 24) });
  }
  return found;
};

const heredocOracle = (code) => heredocOpeners(code)
  .every((h) => h.ok && h.name !== 'EOF');

test('E10: no fixed-EOF heredoc carries a commit message', () => {
  // Pinned block counts, checked BEFORE the oracle runs. `heredocOracle('')` is vacuously true,
  // so every fence-recognizer gap this suite has found — exact info string (r96), column-zero
  // anchor and backtick-only delimiter (r97) — reached the assertion as a shrunken input rather
  // than as a failure. A count that must not drop is what turns "the oracle passed" into
  // "the oracle passed on the whole document". Update it deliberately when a fence is added.
  const PINNED_BASH_LINES = { 'execute-mode.md': 5, 'SKILL.md': 115 };
  for (const [name, path] of [['execute-mode.md', execModePath], ['SKILL.md', skillPath]]) {
    assert.equal(bashBlocks(path).split('\n').length, PINNED_BASH_LINES[name],
      `${name}: the scanned bash surface changed size — a shrinking one means a fence form the `
      + 'extractor stopped recognizing, which passes this oracle by emptying it');
    const openers = heredocOpeners(bashBlocks(path));
    // Named individually so a failure says which spelling, not just "the file is bad".
    for (const h of openers) {
      assert.equal(h.ok, true,
        `${name}: a bash block here may not contain \`<<\` except as a canonical heredoc opener `
        + `spelled <<'NAME' or <<-'NAME'. This rejects \`<<\` in strings, arithmetic and trailing `
        + `comments too — a stated subset, not a parse. Saw ${JSON.stringify(h.name)}`);
      assert.notEqual(h.name, 'EOF', `${name} must not use a fixed EOF heredoc`);
    }
    assert.equal(heredocOracle(bashBlocks(path)), true, `${name} must not use a fixed EOF heredoc`);
  }
});

test('E12: an extended fence info string does not hide a bash block from the oracle', () => {
  // Codex, round 96: `^```bash\n` matched an exact info string, so moving a manual-command fence
  // to ```` ```bash title=manual ```` and giving it a fixed `EOF` delimiter left the unsafe
  // heredoc rendered, copyable, and invisible to E10 — with the other exact fences still present,
  // so the oracle never degraded to an obviously empty input either.
  const asBash = (doc) => fencedBlocks(doc)
    .filter((b) => /^(bash|sh|shell)\b/.test(b.info)).map((b) => b.body).join('\n');

  const extended = "```bash title=manual\ncat <<'EOF'\nmsg\nEOF\n```\n";
  assert.notEqual(asBash(extended), '', 'a fence carrying info-string attributes is still bash');
  assert.equal(heredocOracle(asBash(extended)), false, 'and its heredoc must be judged, not skipped');

  // Nesting, by CommonMark run length: a four-backtick markdown example is one block, and the
  // three-backtick bash fence inside it is what a reader actually copies — so it is scanned too.
  const nested = "````markdown\n```bash\ncat <<'EOF'\nmsg\nEOF\n```\n````\n";
  assert.equal(heredocOracle(asBash(nested)), false, 'a bash fence inside an example is still copyable');

  // Codex, round 97: the opener was anchored at column 0 and to backticks, so two more CommonMark
  // fence forms rendered as copyable bash while handing the oracle an empty string. SKILL.md
  // already ships two three-space-indented ```bash fences, which is how the indented case was
  // confirmed against the repository rather than assumed — before this, E10 had never read them.
  const indented = "   ```bash\n   cat <<'EOF'\n   msg\n   EOF\n   ```\n";
  assert.notEqual(asBash(indented), '', 'a fence indented up to three spaces is still a fence');
  assert.equal(heredocOracle(asBash(indented)), false, 'and its heredoc must be judged, not skipped');
  assert.equal(asBash(indented).includes('\n   '), false,
    'the body is de-indented by the opener, so an indented fence scans identically to a flush one');

  const tilde = "~~~bash\ncat <<'EOF'\nmsg\nEOF\n~~~\n";
  assert.notEqual(asBash(tilde), '', 'a ~~~ fence is a fence');
  assert.equal(heredocOracle(asBash(tilde)), false, 'and its heredoc must be judged too');

  // Delimiter TYPE, not just run length: `~~~` must not close a backtick fence, or the block ends
  // early and everything after the false terminator drops off the scanned surface.
  const crossed = "```bash\ncat <<'EOF'\n~~~\nmsg\nEOF\n```\n";
  assert.equal(heredocOracle(asBash(crossed)), false,
    'a tilde run inside a backtick fence is content — the heredoc after it must still be seen');

  // Negative control: a fence that is not bash must not be scanned as bash, or every prose
  // example naming the construct becomes a failure.
  assert.equal(asBash("```text\ncat <<'EOF'\n```\n"), '', 'a text fence is not a bash block');
  assert.equal(asBash("~~~text\ncat <<'EOF'\n~~~\n"), '', 'and neither is a non-bash tilde fence');
});

test('E11: E10 mutation control — the oracle rejects an injected fixed-EOF heredoc', () => {
  const real = bashBlocks(skillPath);
  assert.equal(heredocOracle(real), true, 'the oracle accepts the shipped file');
  // One control per shell spelling. Three of these four used to pass E10 while ending on an
  // identical `EOF` line, so a single-spelling control was the reason the gap survived.
  for (const spelling of [
    "<<'EOF'", '<<EOF', '<<"EOF"', '<<\\EOF', '<<- EOF',
    // The quote-removal family: each splits the delimiter word so that no single quoting
    // component spells `EOF`. The first four were run under bash 3.2.57 and each terminated on
    // a plain `EOF` line; the last is a syntax error there and is listed because the spelling
    // rule rejects it on FORM, which is the property being tested.
    '<<E"OF"', "<<'E'OF", '<<\\E\\O\\F', "<<$'EOF'", "<<EOF'",
  ]) {
    const mutated = real.replace("<<'SD0X_MSG_EOF'", spelling);
    assert.notEqual(mutated, real, `the ${spelling} mutation must apply — otherwise E10 proves nothing`);
    assert.equal(heredocOracle(mutated), false, `and the oracle must reject ${spelling}`);
  }
  // A here-string is not a heredoc and must not be swept up — it has no terminator line at all,
  // so treating `<<<` as a fixed-EOF heredoc would be a false alarm with no failure behind it.
  assert.equal(heredocOracle("cat <<<EOF\n"), true, 'a here-string is not a heredoc');
  // A redirection may sit directly against the delimiter. Bash runs this; rejecting it would
  // block a legitimate canonical heredoc on punctuation alone.
  assert.equal(heredocOracle("cat <<'SAFE'>out\n"), true,
    'a canonical heredoc followed by a redirection is still canonical');
  // And a `<<EOF` inside a comment opens nothing. Without this the spelling rule makes the
  // construct undiscussable in the very files that document it.
  assert.equal(heredocOracle('# never write <<EOF here\ncat <<\'SAFE\'\n'), true,
    'a heredoc named only in a comment is not a heredoc');
  // The negative control: a delimiter that merely CONTAINS the word must still pass, or the
  // oracle is a substring match wearing a parser's name.
  const renamed = real.replace("<<'SD0X_MSG_EOF'", "<<'MSG_EOF_MARKER'");
  assert.notEqual(renamed, real, 'the negative-control mutation must apply');
  assert.equal(heredocOracle(renamed), true,
    'a delimiter containing EOF as a substring is not a fixed EOF delimiter');
});

// ═══════════════════════════════════════════════════
// Group F: round-41 review findings
// ═══════════════════════════════════════════════════

// Round 44: F1 scans execute-mode.md only, so it stayed green while the WORKFLOW around
// it — `git add`, the post-commit `git log`, the Step 6 `git status` in SKILL.md — kept
// running bare. Inherited GIT_* would then let planning and staging target one repository
// while validation and the commit target another, which is the same split F1 exists to
// forbid, one level up. The policy binds what the skill EXECUTES; the commands it prints
// for the user to run in their own shell are explicitly out of scope, so the sweep skips
// the fences that are quoted output (they sit inside ````markdown wrappers).
test('F1b: SKILL.md applies the same git environment policy to what the skill runs', () => {
  const raw = readFileSync(skillPath, 'utf8');
  assert.match(raw, /### Git Environment Policy/,
    'the policy must be declared once, at workflow level');
  assert.match(raw, /GIT_ENV="env -u GIT_DIR -u GIT_WORK_TREE -u GIT_COMMON_DIR -u GIT_INDEX_FILE -u GIT_OBJECT_DIRECTORY -u GIT_ALTERNATE_OBJECT_DIRECTORIES -u GIT_NAMESPACE -u GIT_CEILING_DIRECTORIES -u GIT_GLOB_PATHSPECS -u GIT_ICASE_PATHSPECS -u GIT_NOGLOB_PATHSPECS -u GIT_LITERAL_PATHSPECS -u GIT_CONFIG -u GIT_CONFIG_PARAMETERS -u GIT_CONFIG_COUNT -u GIT_IMPLICIT_WORK_TREE -u GIT_GRAFT_FILE -u GIT_SHALLOW_FILE -u GIT_PREFIX -u GIT_NO_REPLACE_OBJECTS -u GIT_REPLACE_REF_BASE -u ALLOW_AI_COAUTHOR"/,
    'and it must be the identical prefix execute-mode.md uses');

  // Only the fences the skill itself executes: a ````markdown wrapper marks a block as
  // output for the user, and those are exempt by the stated policy.
  const executed = raw.replace(/^````markdown[\s\S]*?^````$/gm, '');
  const fences = executed.match(/^```bash\n([\s\S]*?)^```$/gm) || [];
  const calls = fences.join('\n')
    .split('\n')
    .filter((l) => /(^|[;&|(]|\s)git\s/.test(l) && !/^\s*#/.test(l));
  assert.ok(calls.length >= 8, `expected the skill's own git calls; found ${calls.length}`);
  for (const call of calls) {
    assert.match(call, /\$GIT_ENV git/,
      `every git call the skill runs must carry the one policy — this one does not: ${call.trim()}`);
    // Round 48, P1: paths are collected root-relative, so a command that consumes them
    // while running from the skill's cwd reads or stages the wrong base. `-C` is not a
    // property of the commands that print — it is a property of all of them.
    if (/rev-parse --show-toplevel/.test(call)) continue;
    assert.match(call, /\$GIT_ENV git -C "\$REPO_ROOT"/,
      `every git call must be pinned to the derived root: ${call.trim()}`);
  }

  // Round 50, P2: the printed `add` operands were checked but the fences that CONSUME a
  // path were not, so Step 5a still diffed raw `<files>` — reading `report1.md` while the
  // commit stages the literal `report[1].md`. Every operand after `--` must be literal.
  for (const call of calls) {
    // Drop a trailing `# comment` before splitting: its words are prose, not operands.
    const after = (call.split(' -- ')[1] || '').replace(/\s#.*$/, '');
    if (/^\s*$/.test(after)) continue;
    for (const o of after.split(/\s+/).filter((w) => w && w !== '…')) {
      assert.match(o, /:\(literal\)/,
        `a path operand must carry :(literal) — this one does not: ${call.trim()}`);
    }
  }

  // Each fence is a separate shell, so a fence that USES either half of the contract must
  // establish BOTH in the same shell. Round 48, P2: asserting only that the assignment
  // *starts* with the list let one full copy elsewhere in the file satisfy the separate
  // full-list check while an individual fence carried a shortened one; and nothing checked
  // REPO_ROOT at all, so `-C ""` (or an abort under nounset) passed.
  for (const fence of fences) {
    if (!/\$GIT_ENV/.test(fence)) continue;
    assert.ok(fence.includes(`GIT_ENV="${CANONICAL_PREFIX}"`),
      `a fence using $GIT_ENV must assign the canonical prefix in the same shell: ${fence.slice(0, 80)}`);
    if (!/\$REPO_ROOT/.test(fence)) continue;
    assert.match(fence, /REPO_ROOT=\$\(\$GIT_ENV git rev-parse --show-toplevel && printf \.\) \|\| \{[^}]*\}\nREPO_ROOT=\$\{REPO_ROOT%\.\}; REPO_ROOT=\$\{REPO_ROOT%\$'\\n'\}/,
      `a fence using $REPO_ROOT must derive it in the same shell: ${fence.slice(0, 80)}`);
  }

  // Round 45: the sweep above matches on the literal token `git `, so a DELEGATED command
  // is invisible to it — `run-skill.sh git-profile git-profile.sh doctor` runs git commands
  // for identity, signing and worktree diagnostics without the word appearing as a command.
  // The preferred diagnostic path was therefore answering about a different repository than
  // the commit while F1b stayed green. The prefix belongs on the delegation, not inside the
  // helper, so that is what is asserted.
  const delegations = executed.split('\n').filter((l) => /run-skill\.sh/.test(l) && !/^\s*#/.test(l));
  assert.ok(delegations.length >= 1, 'the delegated diagnostic must still be present');
  for (const call of delegations) {
    assert.match(call, /\$GIT_ENV /,
      `a helper that runs git must be invoked under the same policy: ${call.trim()}`);
  }

  // The `--execute` script is the one git-running callee invoked WITHOUT the prefix, and it
  // is not a run-skill.sh delegation at all — it establishes its own privileged mode, so the
  // runner would add a hop without adding a guarantee. It carries the identical policy as a
  // process-wide unset; prefixing it would state one policy twice rather than add a second.
  // Asserted unconditionally: an earlier version keyed this off "is it in the delegation
  // list", which quietly became a no-op the moment the invocation stopped going through the
  // runner — a check that cannot fail is not a check.
  const execCalls = executed.split('\n')
    .filter((l) => /smart-commit-execute\.sh|"\$EXECUTE"/.test(l) && !/^\s*#/.test(l));
  assert.ok(execCalls.length >= 1, 'the skill must still invoke the --execute script');
  const src = readFileSync(resolve(__dirname, '../../skills/smart-commit/scripts/smart-commit-execute.sh'), 'utf8');
  const unset = (src.match(/^unset GIT_DIR[\s\S]*?ALLOW_AI_COAUTHOR$/m) || [''])[0]
    .replace(/\\\n\s*/g, ' ');
  for (const tok of REQUIRED_ENV_TOKENS) {
    assert.ok(unset.includes(tok.replace('-u ', '')),
      `smart-commit-execute.sh must strip ${tok} itself, since it is invoked without the prefix`);
  }
  for (const call of execCalls) {
    assert.doesNotMatch(call, /\$GIT_ENV /,
      `the script applies the policy itself; prefixing it states it twice: ${call.trim()}`);
  }
  // Root-anchoring applies to EVERY delegation, self-policing or not — it is about where the
  // wrapper is found, not about the environment. Round 49, P2: the policy claims the skill
  // works from anywhere inside the repository, but the wrapper was still named cwd-relative.
  // From a subdirectory it is simply not found, and the preferred doctor degrades silently to
  // the warn-only inline fallback — losing linked-worktree and signing-key diagnostics.
  for (const call of delegations) {
    assert.match(call, /"\$REPO_ROOT\/scripts\/run-skill\.sh"/,
      `the wrapper must be resolved against the repository root, not the cwd: ${call.trim()}`);
  }
});

test('F1f: the shipped hook resolver answers correctly from a subdirectory', () => {
  // Round 50, P2. The compressed Step 1e resolver looked fine and was wrong: `--git-path`
  // answers relative to ITS OWN cwd, so testing the result from the caller's directory
  // reported "missing" for an installed hook whenever /smart-commit ran from a subdirectory.
  // It also re-implemented core.hooksPath resolution, breaking `~/hooks` and `%(prefix)/…`
  // — which `--git-path` had already expanded correctly. No textual assertion could see any
  // of that, and a mutation reverting the fix left the whole suite green. So this extracts
  // the shipped fence and RUNS it, from a subdirectory, against a real repository.
  const raw = readFileSync(skillPath, 'utf8');
  const m = raw.match(/\*\*1e\. AI Guard Readiness\*\*\s*```bash\n([\s\S]*?)^```$/m);
  assert.ok(m, 'the Step 1e fence must be locatable');
  const fence = m[1];
  assert.match(fence, /guard:installed/, 'the extracted span must be the resolver itself');

  const dir = mkdtempSync(resolve(tmpdir(), 'smart-commit-hook-'));
  // Round 51, P2: the custom-hooksPath cases used to run with the DEFAULT hook still
  // executable, so a mutant that hardcoded `$REPO_ROOT/.git/hooks/commit-msg` passed every
  // one of them. The default hook is removed before those cases, which is the only way the
  // assertions can be about core.hooksPath at all. The fence's exit status is checked too:
  // a resolver that aborts and prints nothing is not the same as one that answers.
  const runFrom = (cwd, env = {}) => {
    const r = spawnSync('bash', ['-c', fence], { cwd, encoding: 'utf8', env: { ...process.env, ...env } });
    assert.equal(r.status, 0, `the resolver must exit 0; got ${r.status}: ${r.stderr}`);
    return r.stdout.trim();
  };
  try {
    const git = (...a) => {
      const r = spawnSync('git', ['-C', dir, ...a], { encoding: 'utf8' });
      assert.equal(r.status, 0, `git ${a.join(' ')} failed: ${r.stderr}`);
      return r;
    };
    git('init', '-q');
    mkdirSync(resolve(dir, 'sub/deep'), { recursive: true });
    const sub = resolve(dir, 'sub/deep');

    assert.equal(runFrom(sub), 'guard:missing', 'no hook installed → missing');

    const hook = resolve(dir, '.git/hooks/commit-msg');
    writeFileSync(hook, '#!/bin/sh\nexit 0\n');
    chmodSync(hook, 0o644);
    assert.equal(runFrom(sub), 'guard:not-executable', 'present but not executable is its own state');
    chmodSync(hook, 0o755);
    assert.equal(runFrom(dir), 'guard:installed', 'from the root');
    assert.equal(runFrom(sub), 'guard:installed',
      'and from a subdirectory — the answer must not depend on where the caller stands');

    // From here the default location must NOT answer, or the custom cases prove nothing.
    rmSync(hook, { force: true });
    assert.equal(runFrom(sub), 'guard:missing', 'control: the default hook is gone');

    // A relative core.hooksPath resolves against the repo root, and `--git-path` is what
    // knows that. Re-deriving it by hand is what broke ~ and %(prefix).
    const install = (p) => {
      mkdirSync(resolve(p), { recursive: true });
      writeFileSync(resolve(p, 'commit-msg'), '#!/bin/sh\nexit 0\n');
      chmodSync(resolve(p, 'commit-msg'), 0o755);
    };
    install(resolve(dir, 'myhooks'));
    git('config', 'core.hooksPath', 'myhooks');
    assert.equal(runFrom(sub), 'guard:installed', 'relative core.hooksPath, seen from a subdirectory');
    git('config', 'core.hooksPath', resolve(dir, 'myhooks'));
    assert.equal(runFrom(sub), 'guard:installed', 'absolute core.hooksPath');

    // `~` expansion is git's, not the shell's — the hand-rolled version produced
    // `$REPO_ROOT/~/hooks/commit-msg`. HOME is redirected so the case is hermetic.
    const home = resolve(dir, 'fakehome');
    install(resolve(home, 'hooks'));
    git('config', 'core.hooksPath', '~/hooks');
    assert.equal(runFrom(sub, { HOME: home }), 'guard:installed', 'core.hooksPath=~/hooks');

    // Round 52, P2: the cases above are all satisfiable by a mutant that re-implements
    // core.hooksPath for the relative/absolute/`~` forms and otherwise falls back to a
    // hardcoded `$REPO_ROOT/.git/hooks/commit-msg`. The two fixtures below are the ones such
    // a mutant cannot pass, because each is a place where `$REPO_ROOT/.git` is not the answer.

    // (1) `%(prefix)` expands to git's own install prefix — NOT to anything under the repo.
    // The literal directory a hand-rolled resolver would build is created and armed, so the
    // truthful answer is `missing` and only the mutant reports a hook here.
    // Round 53, P2: the first version used `%(prefix)/opt/hooks`, whose EXPANDED target this
    // test does not control — on a machine that happens to have an executable hook there, the
    // correct resolver answers `installed` and the test fails for a reason that is not a
    // defect. The tail is taken from the mkdtemp-unique directory name instead. Stated
    // precisely (round 54): mkdtemp guarantees the basename was unused in the temp parent,
    // NOT that it is absent under git's install prefix — so this is collision-RESISTANT,
    // not hermetic. A collision would need `<git-prefix>/sd0x-hookprobe-<generated>/commit-msg`
    // to exist and be executable; the repo-relative trap, by contrast, certainly does exist.
    const unique = `sd0x-hookprobe-${dir.split('/').pop()}`;
    const trapRel = `%(prefix)/${unique}`;
    install(resolve(dir, trapRel));
    assert.ok(statSync(resolve(dir, trapRel, 'commit-msg')).mode & 0o100,
      'fixture precondition: the repo-relative trap is armed, so `missing` means the resolver refused it');
    git('config', 'core.hooksPath', trapRel);
    assert.equal(runFrom(sub), 'guard:missing',
      '%(prefix) is git\'s install prefix; a repo-relative reading of it is the mutant\'s answer');
    // Known limit, stated rather than papered over: this does NOT kill a resolver that
    // special-cases every `%(prefix)` path as missing. Killing that one needs an executable
    // hook at the expanded target — inside git's install prefix — which no hermetic test may
    // create. The fixtures below cover the mutants that are reachable.

    // (2) In a linked worktree `.git` is a FILE, and the hooks live in the common dir. The
    // resolver must be asked; `$REPO_ROOT/.git/hooks/commit-msg` is not even a directory path.
    git('config', '--unset', 'core.hooksPath');
    install(resolve(dir, '.git/hooks'));
    git('-c', 'user.email=t@example.com', '-c', 'user.name=t', 'commit', '-q', '--allow-empty', '-m', 'init');
    const wt = resolve(dir, 'wt');
    git('worktree', 'add', '-q', wt, '-b', 'probe');
    assert.ok(statSync(resolve(wt, '.git')).isFile(), 'fixture precondition: a linked worktree\'s .git is a file');
    assert.equal(runFrom(wt), 'guard:installed',
      'the common-dir hook governs the worktree — only git knows where it is');

    // (3) A submodule working directory is the same class by a different route: `.git` is a
    // file again, but the gitdir lives at `<super>/.git/modules/<name>`, which no rule about
    // worktrees would produce either. Measured, not assumed.
    const superDir = resolve(dir, 'super');
    mkdirSync(superDir, { recursive: true });
    const sup = (...a) => {
      const r = spawnSync('git', ['-C', superDir, '-c', 'user.email=t@example.com',
        '-c', 'user.name=t', '-c', 'protocol.file.allow=always', ...a], { encoding: 'utf8' });
      assert.equal(r.status, 0, `git ${a.join(' ')} failed: ${r.stderr}`);
    };
    sup('init', '-q');
    sup('commit', '-q', '--allow-empty', '-m', 'init');
    sup('submodule', 'add', '-q', dir, 'vendor');
    const vendor = resolve(superDir, 'vendor');
    assert.ok(statSync(resolve(vendor, '.git')).isFile(), 'fixture precondition: a submodule\'s .git is a file');
    assert.equal(runFrom(vendor), 'guard:missing', 'control: the submodule gitdir has no hook yet');
    install(resolve(superDir, '.git/modules/vendor/hooks'));
    assert.equal(runFrom(vendor), 'guard:installed',
      'the hook lives under .git/modules/<name> — neither $REPO_ROOT/.git nor a worktree rule finds it');
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('F1g: a repository root ending in a newline survives the derivation', () => {
  // Round 54, P2. `$( )` strips EVERY trailing newline, so the direct form truncated the
  // last component of such a root and every later `git -C "$REPO_ROOT"` named a path that
  // does not exist. Round 53 recorded this as a third-party limitation because `rev-parse
  // --show-toplevel` has no `-z` form — which is true and does not follow: a sentinel
  // appended INSIDE the substitution lets exactly one record terminator be removed and
  // nothing else. Measured: the shipped form answers `installed`, the direct form `missing`.
  const raw = readFileSync(skillPath, 'utf8');
  const m = raw.match(/\*\*1e\. AI Guard Readiness\*\*\s*```bash\n([\s\S]*?)^```$/m);
  assert.ok(m, 'the Step 1e fence must be locatable');
  const fence = m[1];
  assert.match(fence, /printf \.\)[^\n]*\nREPO_ROOT=\$\{REPO_ROOT%\.\}/,
    'the derivation must carry the sentinel — without it this test proves nothing');

  const dir = mkdtempSync(resolve(tmpdir(), 'smart-commit-nl-'));
  const root = resolve(dir, 'repo') + '\n';        // the last component ENDS in a newline
  try {
    mkdirSync(root, { recursive: true });
    const git = (...a) => {
      const r = spawnSync('git', ['-C', root, ...a], { encoding: 'utf8' });
      assert.equal(r.status, 0, `git ${a.join(' ')} failed: ${r.stderr}`);
    };
    git('init', '-q');
    const hooks = resolve(root, '.git/hooks');
    mkdirSync(hooks, { recursive: true });
    writeFileSync(resolve(hooks, 'commit-msg'), '#!/bin/sh\nexit 0\n');
    chmodSync(resolve(hooks, 'commit-msg'), 0o755);

    const run = (body) => spawnSync('bash', ['-c', body], { cwd: root, encoding: 'utf8' });
    const shipped = run(fence);
    assert.equal(shipped.status, 0, `the resolver must exit 0; got ${shipped.stderr}`);
    assert.equal(shipped.stdout.trim(), 'guard:installed',
      'the shipped derivation keeps the trailing newline, so -C names the real repository');

    // Control: the pre-fix derivation on the same fixture. If this ever also says
    // `installed`, the fixture stopped reproducing the defect and the test is vacuous.
    const direct = fence.replace(
      /REPO_ROOT=\$\(\$GIT_ENV git rev-parse --show-toplevel && printf \.\) \|\| \{[^}]*\}\nREPO_ROOT=\$\{REPO_ROOT%\.\}; REPO_ROOT=\$\{REPO_ROOT%\$'\\n'\}/,
      'REPO_ROOT=$($GIT_ENV git rev-parse --show-toplevel)');
    assert.notEqual(direct, fence, 'the control must actually differ from the shipped form');
    assert.equal(run(direct).stdout.trim(), 'guard:missing',
      'control: the direct substitution truncates the root and finds nothing');
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('F1h: a failed root derivation is reported, not swallowed by the sentinel', () => {
  // Round 55, P2. The sentinel that fixed round 54 introduced its own defect: with
  // `git …; printf .` the LAST command in the substitution is `printf`, whose exit 0
  // becomes the assignment's status. Every documented `|| { cleanup; exit; }` was then
  // attached to something that could not fail, and a failed lookup silently became
  // REPO_ROOT="" — after which `git -C ""` acts on the current directory instead.
  // `&&` keeps the byte handling identical and lets git's status through.
  const raw = readFileSync(skillPath, 'utf8');
  const m = raw.match(/\*\*1e\. AI Guard Readiness\*\*\s*```bash\n([\s\S]*?)^```$/m);
  assert.ok(m, 'the Step 1e fence must be locatable');
  const fence = m[1];

  // Round 56, P2: the first version of this test built its own `||` around the derivation
  // and asserted on that. It therefore proved the substitution CAN report a failure, not
  // that the shipped fence DOES anything with it — and the shipped Step 1e did not: outside
  // a repository it printed `guard:missing` and exited 0, reporting "the hook is not
  // installed" when the truth was "this is not a repository". The fence itself is now run,
  // verbatim, and the guard is part of it.
  assert.match(fence, /^REPO_ROOT=\$\(\$GIT_ENV git rev-parse --show-toplevel && printf \.\) \|\|/m,
    'the guard must be part of the shipped derivation, not synthesized by this test');

  // A directory that is not a repository and has no repository above it, so
  // `rev-parse --show-toplevel` genuinely fails rather than answering about us.
  const dir = mkdtempSync(resolve(tmpdir(), 'smart-commit-status-'));
  try {
    // The fixture depends on there being no repository ABOVE the temp directory — assert it
    // rather than assume it, or on a host where tmpdir() sits inside a checkout the probe
    // would answer about that repository and both branches would look identical.
    assert.notEqual(
      spawnSync('git', ['rev-parse', '--show-toplevel'], { cwd: dir, encoding: 'utf8' }).status, 0,
      'fixture precondition: the temp directory must not be inside any repository');
    const run = (body) => spawnSync('bash', ['-c', body], { cwd: dir, encoding: 'utf8' });

    const shipped = run(fence);
    assert.notEqual(shipped.status, 0,
      'outside a repository the shipped fence must fail, not answer about the guard');
    assert.doesNotMatch(shipped.stdout, /guard:/,
      'and it must not report a guard verdict at all — `guard:missing` here would mean '
      + '"the hook is not installed" when the truth is "this is not a repository"');

    // Control: revert only the guard. If this ever also refuses to answer, the fixture has
    // stopped reproducing the defect and the assertions above prove nothing.
    const unguarded = fence.replace(/ \|\| \{ echo "[^"]*" >&2; exit 1; \}/, '');
    assert.notEqual(unguarded, fence, 'the control must actually differ from the shipped form');
    const ctl = run(unguarded);
    assert.equal(ctl.status, 0, 'control: without the guard the fence exits 0…');
    assert.match(ctl.stdout, /guard:missing/, '…and misreports the missing repository as a missing hook');
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('F1c: manual mode binds the printed commands to the repository the plan describes', () => {
  // Round 45, P1. The plan is computed under GIT_ENV; the printed commands were bare. With
  // GIT_DIR/GIT_WORK_TREE inherited those name different repositories, so the user pastes
  // commands that stage and commit somewhere no plan was ever shown for. Not an authority
  // question — the user does own their shell — but plan/action coherence.
  // Round 46: the first version of this test asserted on VOCABULARY — the heading, three
  // variable names, `$GIT_ENV`, a phrase. Codex mutated the paragraph to say every command
  // may stay bare, kept those tokens, and the test still passed. An oracle that a semantic
  // reversal satisfies is not an oracle. So this one reads the commands the skill actually
  // prints and requires each to be self-contained: no reliance on the reader's cwd (`-C`)
  // and none on their git environment (`env -u`), with `env` spelled out because the user's
  // shell has no `$GIT_ENV`. Weaken the rule and the shipped examples must be weakened with
  // it, which is what this fails on.
  const raw = readFileSync(skillPath, 'utf8');
  // Round 47: the stripped set grew (GIT_INDEX_FILE and friends repoint the index and object
  // store without touching GIT_DIR), and the root is now quoted. Both are asserted literally:
  // a shortened list or a bare root is exactly the regression this exists to catch.
  // Assignments may follow the `-u` flags (that is how the --ai-co-author opt-in is expressed
  // and the only legal place for one); nothing else may come between the prefix and `git`.
  const SELF_CONTAINED = new RegExp(
    CANONICAL_PREFIX.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    + String.raw`(?: [A-Z_]+=\S+)* git -C '<REPO_ROOT>' `);
  assert.match(raw, /\*\*Repository coherence\*\*/, 'manual mode must state the coherence rule');

  // The printed commands: the ````markdown example blocks plus the post-execution checklist.
  const printed = (raw.match(/^````markdown\n([\s\S]*?)^````$/gm) || []).join('\n')
    + '\n' + (raw.match(/## Post-Execution Checklist[\s\S]*?```/m) || [''])[0];
  // `git -C <REPO_ROOT> commit` puts options between the two words, so the subcommand is not
  // adjacent to `git` — matching `git commit` literally finds nothing once the fix is applied.
  const cmds = printed.split('\n').filter((l) => /\bgit\b[^\n]*\b(add|commit|status|log)\b/.test(l));
  assert.ok(cmds.length >= 5, `expected the printed commands; found ${cmds.length}`);
  for (const c of cmds) {
    assert.match(c, SELF_CONTAINED,
      `a printed command must be self-contained — cwd and git env independent: ${c.trim()}`);
  }
  assert.ok(!/\$GIT_ENV git/.test(printed),
    'printed output must not reference $GIT_ENV — that variable exists only in the skill\'s shell');

  // Round 47: pathspecs are resolved against `-C`, so an `add` must pass them root-relative,
  // single-quoted, after `--`. Without the quoting a filename with a space becomes two
  // pathspecs and one with a leading dash becomes a flag — on a command the user pastes.
  for (const c of cmds.filter((l) => /\badd\b/.test(l))) {
    assert.match(c, / -- (\\|$)/,
      `pathspecs must follow \`--\` so option-like filenames cannot become flags: ${c.trim()}`);
  }
  // Round 48, P2: requiring *a* quoted operand let the second one lose its quotes silently.
  // Every operand on the continuation lines is checked, and there must be more than one —
  // otherwise collapsing the example to a single path would make the rule unfalsifiable.
  const addBlock = printed.slice(printed.indexOf(' add -- '));
  // Continuation lines only: the `add` line ends with a backslash, and each following line
  // is operands until one does not continue. Slicing a fixed count would swallow the next
  // command and fail on the word `env` instead of on an unquoted path.
  const addLines = addBlock.split('\n');
  const operandLines = [];
  for (let i = 0; i < addLines.length && /\\$/.test(addLines[i]); i += 1) {
    operandLines.push(addLines[i + 1]);
  }
  const operands = operandLines
    .flatMap((l) => (l || '').replace(/\\$/, '').trim().split(/\s+/)).filter(Boolean);
  assert.ok(operands.length >= 2, `expected several printed pathspecs; found ${operands.length}`);
  for (const o of operands) {
    assert.match(o, /^'[^']+'$/, `every printed pathspec must be single-quoted: ${o}`);
    // Round 49: quoting is the shell layer only. Literality is per-operand — an exported
    // GIT_LITERAL_PATHSPECS would also reach the repository's hooks and break their globs.
    assert.match(o, /^':\(literal\)/, `every printed pathspec must be literal: ${o}`);
  }

  // The --ai-co-author variant is described in prose rather than shown as a block. Codex
  // mutated that sentence to a bare `ALLOW_AI_COAUTHOR=1 git commit …` and this test stayed
  // green, so the sentence is pinned too: it must say the whole self-contained form is kept.
  const aiIdx = raw.indexOf('With `--ai-co-author`');
  assert.ok(aiIdx > 0, 'the --ai-co-author variant must still be described');
  // Round 49, P2: judging the variant by scanning its PROSE matched zero spans, so a rewrite
  // saying the variant drops the prefix passed an empty loop. The variant is now emitted as a
  // real ````markdown block, which puts it inside `cmds` above — the same self-contained rule
  // every other printed command is held to, with no separate oracle to go stale. What is left
  // to pin is that it exists, carries the assignment AFTER the prefix, and appends the one
  // permitted trailer.
  const aiCmds = cmds.filter((c) => /ALLOW_AI_COAUTHOR=1/.test(c));
  assert.equal(aiCmds.length, 1, `the --ai-co-author command must be shown once; found ${aiCmds.length}`);
  assert.match(aiCmds[0], new RegExp(
    SELF_CONTAINED.source.replace(String.raw`(?: [A-Z_]+=\S+)*`, ' ALLOW_AI_COAUTHOR=1')),
    'the assignment must sit AFTER the prefix — before it, the prefix strips it away');
  assert.match(raw.slice(aiIdx, aiIdx + 900), /^Co-Authored-By: Claude <noreply@anthropic\.com>$/m,
    'and the one permitted trailer must be spelled byte-exact');
});

/**
 * Lift the documented resolution loop out of execute-mode.md and make it runnable.
 *
 * Round 42 finding: the previous F2 called `runGuard()`, which uses the constant
 * `guardPath` directly — so it never executed the loop it claimed to prove, and would
 * have passed just the same if the loop had selected the planted guard. This extracts
 * the real text and runs THAT, so a regression in the doc fails the test.
 */
// P2-b: the execute contract needs tools the frontmatter did not pre-authorize, so an
// interactive run prompts and a headless run fails. create-pr pins the same contract.
test('F6: the frontmatter pre-authorizes every tool the execute path uses, and no more', () => {
  const fm = readFileSync(skillPath, 'utf8').split('---')[1];
  for (const [tool, why] of [
    [/\bWrite\b/, 'the commit message is written with the Write tool'],
    [/Bash\(bash:\*\)/, 'smart-commit-execute.sh is launched as `bash -p -- "$EXECUTE" …`'],
    [/Bash\(git:\*\)/, 'the read-only diagnostics and staging are git calls'],
    [/Bash\(env:\*\)/, 'those diagnostics carry the env -u prefix'],
  ]) {
    assert.match(fm, tool, `allowed-tools must cover: ${why}`);
  }
  // The other direction, and the one that decays silently: a grant the skill no longer needs
  // is not inert, it is standing authority. mktemp and rm moved inside the execute script when
  // the procedure stopped being bash Claude assembles, so the grants must have gone with them.
  const grants = ((fm.split('\n').find((l) => /^allowed-tools:/.test(l)) ?? '')
    .match(/Bash\(([^:)]+):\*\)/g) || []).map((g) => g.slice(5, -3)).sort();
  assert.deepEqual(grants, ['bash', 'env', 'git'],
    'the execute path issues exactly one shell command — launching the script');
});
